name: 'Remote Workflow Trigger Action'
description: 'A Github workflow action to call a webhook with payload data from the event. Support for JSON or URL encoded endpoints.'
inputs:
  webhook_url:
    description: 'The HTTP URI of the webhook endpoint to invoke'
    required: true
  webhook_secret:
    description: 'The secret with which a signature hash is generated. If omitted, the URL itself will be used as the value with which to generate the hash.'
    required: true
  
  verbose:
    description: 'Optional, set to true to enable verbose output. Warning: this might lead to domain and IP leaking, as well as other security issues as the logs are public.'

  data:
    description: 'Optional, additional data to include in the payload'
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  # image: 'docker://ghcr.io/distributhor/workflow-webhook-container:v3.0.1'

branding:
  icon: 'terminal'
  color: 'gray-dark'